# Generated by Django 3.0.4 on 2020-04-08 07:51

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import webapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('Hospital', 'Hospital'), ('Supplier', 'Supplier'), ('HospitalGroup', 'HospitalGroup'), ('SystemOperator', 'SystemOperator')], max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('reputation_score', models.FloatField(blank=True, null=True)),
                ('within_group_only', models.BooleanField(default=False)),
                ('contribution', models.IntegerField(default=0)),
                ('projected_load', models.IntegerField(default=0)),
                ('current_load', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_requested', models.IntegerField()),
                ('num_needed', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('time_submitted', models.DateTimeField(auto_now_add=True)),
                ('auto_generated', models.BooleanField(default=False)),
                ('date_allocated', models.DateTimeField(blank=True, null=True)),
                ('date_fulfilled', models.DateTimeField(blank=True, null=True)),
                ('requesting_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requesting_hospital', to='webapp.Hospital')),
                ('sending_hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sending_hospital', to='webapp.Hospital')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentBatches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_batch_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SystemParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_reserve', models.FloatField(default=0.0)),
                ('strategic_reserve', models.FloatField(default=0.0)),
                ('reputation_score_weight', models.FloatField(default=34.0)),
                ('contribution_weight', models.FloatField(default=33.0)),
                ('projected_load_weight', models.FloatField(default=33.0)),
            ],
        ),
        migrations.CreateModel(
            name='VentilatorBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_method', models.CharField(default='Fedex', max_length=100)),
                ('shipment_date', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_number', models.CharField(default='N/A', max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owning_order', to='webapp.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Ventilator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_num', models.CharField(max_length=128)),
                ('state', models.CharField(choices=[('Available', 'Available'), ('Requested', 'Requested'), ('InTransit', 'InTransit'), ('InUse', 'InUse'), ('Reserve', 'Reserve'), ('RequestedReserve', 'RequestedReserve')], default=webapp.models.Ventilator.State['Available'], max_length=100)),
                ('monetary_value', models.IntegerField(default=10000)),
                ('current_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_hospital', to='webapp.Hospital')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.Order')),
                ('owning_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owning_hospital', to='webapp.Hospital')),
                ('ventilator_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventilator_batch', to='webapp.VentilatorBatch')),
            ],
        ),
        migrations.CreateModel(
            name='SystemOperator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='hospital',
            name='hospital_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.HospitalGroup'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
