# Generated by Django 3.0.4 on 2020-04-17 07:19

from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventilator',
            name='quality',
            field=models.CharField(blank=True, choices=[('Poor', 'Poor'), ('Fair', 'Fair'), ('Excellent', 'Excellent')], default=webapp.models.Ventilator.Quality['Poor'], max_length=100, null=True),
        ),
    ]
