# Generated by Django 3.0.4 on 2020-04-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='num_needed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventilator',
            name='monetary_value',
            field=models.IntegerField(default=10000),
        ),
    ]
