# Generated by Django 3.0.4 on 2020-04-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='_last_used_role',
            field=models.BooleanField(default=True),
        ),
    ]
