# Generated by Django 3.0.4 on 2020-04-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventilator',
            name='unknown_status',
            field=models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('InUse', 'In Use'), ('TestingNeeded', 'Testing Needed'), ('InTesting', 'In Testing'), ('NotWorking', 'Not Working'), ('InRepair', 'In Repair')], default='InUse', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ventilator',
            name='status',
            field=models.CharField(choices=[('Unavailable', 'Unavailable'), ('Available', 'Available'), ('Packing', 'Packing'), ('InTransit', 'In Transit'), ('SourceReserve', 'Source Reserve'), ('DestinationReserve', 'Destination Reserve')], default='Unavailable', max_length=100),
        ),
    ]
