# Generated by Django 3.0.4 on 2020-04-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200403_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_num',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
