# Generated by Django 3.0.4 on 2020-03-30 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200330_0315'),
        ('webapp', '0002_auto_20200328_1936'),
    ]

    operations = [
    ]
