# Generated by Django 3.0.4 on 2020-04-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200406_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_allocated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='date_fulfilled',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
