# Generated by Django 3.0.4 on 2020-04-19 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200418_0734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='requested_qty',
            new_name='offered_qty',
        ),
    ]
