# Generated by Django 3.0.4 on 2020-04-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200419_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='shipping_service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ventilator',
            name='unavailable_status',
            field=models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('InUse', 'In Use'), ('PendingOffer', 'Pending Offer'), ('TestingNeeded', 'Testing Needed'), ('InTesting', 'In Testing'), ('NotWorking', 'Not Working'), ('InRepair', 'In Repair')], default='InUse', max_length=100, null=True),
        ),
    ]
