# Generated by Django 3.0.4 on 2020-05-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_shipment_is_requisition'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventilator',
            name='arrived_code',
            field=models.CharField(blank=True, choices=[('NeedsInspection', 'NeedsInspection'), ('PassInspection', 'PassInspection'), ('DestinationReserve', 'DestinationReserve'), ('AvailableForUse', 'AvailableForUse')], default='AvailableForUse', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('PendingApproval', 'PendingApproval'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled'), ('Closed', 'Closed')], default='PendingApproval', max_length=100),
        ),
        migrations.AlterField(
            model_name='ventilator',
            name='status',
            field=models.CharField(choices=[('Unavailable', 'Unavailable'), ('Available', 'Available'), ('Arrived', 'Arrived'), ('Packing', 'Packing'), ('InTransit', 'In Transit'), ('SourceReserve', 'Source Reserve'), ('DestinationReserve', 'Destination Reserve')], default='Unavailable', max_length=100),
        ),
    ]
