# Generated by Django 3.0.4 on 2020-05-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20200501_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('PendingApproval', 'PendingApproval'), ('Approved', 'Approved'), ('Replaced', 'Replaced'), ('Cancelled', 'Cancelled'), ('Closed', 'Closed')], default='PendingApproval', max_length=100),
        ),
    ]
