# Generated by Django 3.0.4 on 2020-05-04 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20200501_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventilator',
            old_name='unavailable_status',
            new_name='unavailable_code',
        ),
        migrations.AlterField(
            model_name='allocation',
            name='status',
            field=models.CharField(choices=[('Allocated', 'Allocated'), ('Cancelled', 'Cancelled'), ('Closed', 'Closed')], default='Allocated', max_length=100),
        ),
    ]
